Changes to ghc(4)
Changes to ghc:
commit 3a04ce29a2d92f58ab07f83f4970c544e4afdf00
Author: Gabor Greif <ggreif@gmail.com>
Date:   Mon May 19 22:50:41 2014 +0200

    Fix below warning by including "unistd.h" also

    exec_signals_prepare.c:26:5: warning: implicit declaration of function 'execv' is invalid in C99
          [-Wimplicit-function-declaration]
        execv(argv[1], argv+1);
        ^
    1 warning generated.

commit a8cba196e9d651571c4902706b73ab0c591dc335
Author: Gabor Greif <ggreif@gmail.com>
Date:   Mon May 19 19:42:07 2014 +0200

    Catch some typos

commit 135489ddc77c6e1b686c0ebf00dee95b218681ed
Author: Gabor Greif <ggreif@gmail.com>
Date:   Fri May 16 19:41:34 2014 +0200

    Provide deprecated backward compatible implementation to 'equalP'

commit 4117551f8822ff76501f9f96186dbd39dda26f1d
Author: Gabor Greif <ggreif@gmail.com>
Date:   Wed May 14 23:41:50 2014 +0200

    Re-add 'classP' with a compatible implementation and a deprecation notice