Changes to ghc
Changes to ghc:
commit 54b31f744848da872c7c6366dea840748e01b5cf
Author: Sergei Trofimovich <slyfox@gentoo.org>
Date:   Sat May 3 22:29:14 2014 +0300

    fix rts exported symbols base_GHCziIOziException_allocationLimitExceeded_closure

    Commit  b0534f78a73f972e279eed4447a5687bd6a8308e added new exported rts symbols,
    but slightly misspelled them.

    Observer on first compiled program:
    > Linking dist/build/haskell-updater/haskell-updater ...
    > /usr/lib64/ghc-7.9.20140503/rts-1.0/libHSrts.a(Schedule.o): In function `scheduleWaitThread':
    > (.text+0xc4c): undefined reference to `base_GHCziIOziException_allocationLimitExceeded_closure'
    > /usr/lib64/ghc-7.9.20140503/rts-1.0/libHSrts.a(RtsStartup.o): In function `hs_init_ghc':
    > (.text+0x2fa): undefined reference to `base_GHCziIOziException_allocationLimitExceeded_closure'
    > collect2: error: ld returned 1 exit status

    CC: Simon Marlow <marlowsd@gmail.com>
    Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>