Changes to ghc
Changes to ghc:
commit 925b0a499dba8a891af06f1bd3f5caf063682b0b
Author: Sergei Trofimovich <slyfox@gentoo.org>
Date:   Thu Feb 20 03:17:27 2014 -0600

    RetainerProfile.c: include missing header (#8810)

    Found by clang:

      rts_dist_HC rts/dist/build/RetainerProfile.p_o

      rts/RetainerProfile.c:1779:5:
         error: implicit declaration of function 'markStableTables' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            markStableTables(retainRoot, NULL);

    Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
    Signed-off-by: Austin Seipp <austin@well-typed.com>