Changes to ghc(10)
Changes to ghc:
commit 1b152a6237ce67559797379b0e77451f621dbe3e
Author: Austin Seipp <austin@well-typed.com>
Date:   Thu Feb 20 06:12:06 2014 -0600

    Add a test for d3af980 (#5682)

    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit 5a576754d745171422d13cd1dba69dd874714cf1)

commit ff57204d6dd32a87999cf467eb327db2f6245b1c
Author: Sergei Trofimovich <slyfox@gentoo.org>
Date:   Thu Feb 20 03:17:27 2014 -0600

    RetainerProfile.c: include missing header (#8810)

    Found by clang:

      rts_dist_HC rts/dist/build/RetainerProfile.p_o

      rts/RetainerProfile.c:1779:5:
         error: implicit declaration of function 'markStableTables' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            markStableTables(retainRoot, NULL);

    Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit 925b0a499dba8a891af06f1bd3f5caf063682b0b)

commit b27517a53ef4a8cdc62d52289600f02e28a46a7c
Author: Austin Seipp <austin@well-typed.com>
Date:   Thu Feb 20 01:28:00 2014 -0600

    Really fix #5682 (parsing of promoted datacons)

    Patch submitted by an anonymous friend on the bug tracker.

    This also fixes TH_RichKinds2 which had a slight message output wibble
    (it uses the qualified name of the promoted datacon)

    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit d3af9807ca8a1db0bc9298ea50895ee9df55edb7)

commit cd10cd4b6509a827fb3278d51d2802dfedd24ddc
Author: Austin Seipp <austin@well-typed.com>
Date:   Thu Feb 20 01:17:57 2014 -0600

    Fix #8801: exclude extra packages from the sdist.

    This is special cased a little since it's cleaner, and we don't
    necessarily want to remove nofib anyway - just the extra packages.

    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit f99a0321a8cf0507924a0d30b6b7b586d7855129)

commit a1e57a0fb1979aeec191c35d96e9b98c03be6c47
Author: Austin Seipp <austin@well-typed.com>
Date:   Wed Feb 19 16:39:50 2014 -0600

    Clear up docs regarding LLVM backend (#8792)

    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit 2b34947b60069e51abfcada9c45a6d7b590f5a2b)

commit 0eb804b5cec38eabc02eed2498c56575d0503977
Author: Austin Seipp <austin@well-typed.com>
Date:   Wed Feb 19 06:31:53 2014 -0600

    Switch on -dynamic-too with QuasiQuotes as well.

    As pointed out by Albert Y. C. Lai on glasgow-haskell-users.

    Signed-off-by: Austin Seipp <austin@well-typed.com>
    (cherry picked from commit e75ebc487b68a07bd632b51df62d9047c559f19f)

commit fd5d7277ec3634989872e2a3f30970633936e1a2
Author: Karel Gardas <karel.gardas@centrum.cz>
Date:   Tue Feb 18 09:22:59 2014 +0100

    fix sed expression in build dependencies rules to work well with non-GNU sed (fixes #8764)

    The patch is provided by Christian Maeder <Christian.Maeder@dfki.de>

    Signed-off-by: Karel Gardas <karel.gardas@centrum.cz>
    Signed-off-by: Austin Seipp <austin@well-typed.com>
    (cherry picked from commit e638acb6a825559fbd93bdaf8ae2704535c157f1)

commit 6c8410d29f6e78c309a6152a62788b3681a3350b
Author: Carter Tazio Schonwald <carter.schonwald@gmail.com>
Date:   Thu Jan 30 12:27:35 2014 -0500

    add more information about the nature of support of prefetch primops on none x86/AMD64 -fasm platforms (and -fvia)
    to the 7.8 release notes

    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit 27fe12856a34488ea94291990238c37e5353d1a3)

commit b4eb13d6a42211681774cc859decf9ab5e64ba7f
Author: Karel Gardas <karel.gardas@centrum.cz>
Date:   Mon Feb 17 10:24:05 2014 +0100

    fix build failure on Solaris 10 due to RANLIB being set to ':' by configure (#8795)

    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit 5c6ced556a989e7fccfa2d4adc6f6bbe538a8e6c)

commit bbac5fe576e412a2b5ffb504a30aaa697318e514
Author: Karel Gardas <karel.gardas@centrum.cz>
Date:   Tue Feb 18 09:18:07 2014 +0100

    add omitted FP_PROG_AR_SUPPORTS_ATFILE into the distribution configure.ac (fixes #8794)

    Signed-off-by: Austin Seipp <austin@well-typed.com>

    (cherry picked from commit 43c314c730d205a3ec8ef5d54e5bf72a7900f01d)